"""
Django settings for todoapp project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
#import django_heroku
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import local
#from django.core.wsgi import get_wsgi_application

sentry_sdk.init(
    # dsn = str(os.environ.get('DSN')),
    dsn = local.dsn,
    integrations=[DjangoIntegration()]
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = str(os.environ.get('SECRET_KEY'))
SECRET_KEY = local.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = local.debug

ALLOWED_HOSTS = ['0.0.0.0','localhost','84.201.136.35']

LOGIN_REDIRECT_URL = "tasks:list"



EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_HOST_USER = str(os.environ.get('EMAIL_HOST_USER'))
# EMAIL_HOST_PASSWORD = str(os.environ.get('EMAIL_HOST_PASSWORD'))
EMAIL_HOST_USER = local.email_host_user
EMAIL_HOST_PASSWORD = local.email_host_password
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = str('Сайт.ру <%s>' % (os.environ.get('EMAIL_HOST_USER')))
# SERVER_EMAIL = str(os.environ.get('EMAIL_HOST_USER'))
SERVER_EMAIL = local.email_host_user





# Application definition

INSTALLED_APPS = [

    #'debug_toolbar', #comment out before upload to heroku
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks.apps.TasksConfig',
    'accounts.apps.AccountsConfig',
    'taggit',
    'tasks.templatetags.custom_tags',
    'trello',



]

MIDDLEWARE = [
    #'debug_toolbar.middleware.DebugToolbarMiddleware', #comment out before upload to heroku
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todoapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test_skillfactory',
        'USER': local.db_user,
        'PASSWORD': local.db_pass,
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
#django_heroku.settings(locals())
#INTERNAL_IPS = ['127.0.0.1', 'localhost'] #comment out before upload to heroku
